import { describe, expect, it } from "vitest";
import { Cl } from "@stacks/transactions";
import { hexToBytes } from "@noble/hashes/utils";

// ---------------------------------------------------------------------------
// REAL Pyth Lazer `evm` golden fixtures -- the byte-order / endianness anchors.
//
// Two externally-produced vectors, neither generated by our own encoder:
//
//   STAGING -- pyth-network/pyth-crosschain lazer/contracts/evm/test/PythLazer.t.sol
//     (fn test_verify), commit fca047c66d4f38f9efd3601feeb93b733aad520d, v0.1.1.
//     Single feed, no confidence; staging signer.
//
//   PRODUCTION -- a real BTC/ETH/SOL update captured from the live Lazer API
//     (scripts/gen-lazer-fixture.mjs -> tests/fixtures/lazer/captured-updates.json),
//     signed by Pyth's PRODUCTION signer. Multi-feed, with confidence + best-bid/ask
//     + publisher-count, so it confirms big-endian layout AND closes the multi-feed /
//     confidence(u64) coverage gaps on real production bytes.
//
// Matching Pyth's own decoded values confirms our parser against production data
// (PLAN Phase 5, sections 9-10).
// ---------------------------------------------------------------------------

const accounts = simnet.getAccounts();
const deployer = accounts.get("deployer")!;

const DECODER = "pyth-lazer-decoder-v1";
const GOV = "pyth-lazer-governance";

const FAR_FUTURE = 100_000_000_000n; // unix seconds, ~year 5138 -- never expired
const ERR_UNTRUSTED_SIGNER = 2105;

const optInt = (v: bigint | null) => (v === null ? Cl.none() : Cl.some(Cl.int(v)));
const optUint = (v: bigint | null) => (v === null ? Cl.none() : Cl.some(Cl.uint(v)));

// Expected decoded per-feed tuple (full v1 shape). ema-* and feed-update-timestamp
// are never produced by the v1 decoder, so they are always `none`.
const feedRecord = (
  id: number,
  price: bigint,
  expo: bigint,
  conf: bigint | null,
  pub: bigint | null,
  bid: bigint | null,
  ask: bigint | null,
) =>
  Cl.tuple({
    "feed-id": Cl.uint(id),
    price: Cl.some(Cl.int(price)),
    exponent: Cl.some(Cl.int(expo)),
    confidence: optUint(conf),
    "publisher-count": optUint(pub),
    "best-bid": optInt(bid),
    "best-ask": optInt(ask),
    "ema-price": Cl.none(),
    "ema-confidence": Cl.none(),
    "feed-update-timestamp": Cl.none(),
  });

function trust(signerHex: string) {
  simnet.callPublicFn(
    GOV,
    "set-trusted-signers",
    [Cl.list([Cl.tuple({ pubkey: Cl.buffer(hexToBytes(signerHex)), "expires-at": Cl.uint(FAR_FUTURE) })])],
    deployer,
  );
}

// === STAGING vector (PythLazer.t.sol v0.1.1) ===============================
// Properties (out of type order): Price, BestAsk(0), BestBid(0), PublisherCount(1),
// Exponent(-8); no confidence. BestBid/BestAsk are 0 -- Lazer's "missing" sentinel
// for optionals -- so they decode to `none` (decoder `some-if-nonzero-*`), matching
// the reference PythLazerLib (a 0 optional => ApplicableButMissing).
const STAGING_UPDATE = hexToBytes(
  "2a22999a9ee4e2a3df5affd0ad8c7c46c96d3b5ef197dd653bedd8f44a4b6b69" +
    "b767fbc66341e80b80acb09ead98c60d169b9a99657ebada101f447378f227bf" +
    "fbc69d3d01003493c7d37500062cf28659c1e801010000000605000000000005" +
    "f5e10002000000000000000001000000000000000003000104fff8",
);
const STAGING_PAYLOAD = STAGING_UPDATE.slice(71);
// Compressed pubkey recovered off-chain (eth 0xb8d50f0bAE75BF6E03c104903d7C3aFc4a6596Da).
const STAGING_SIGNER = "033fa670134f8f961047bf009e0e4907c79005fdf83eef5eef13d2f36bb5cd048b";
const STAGING_DECODE = Cl.tuple({
  timestamp: Cl.uint(1_738_270_008_001_000n),
  channel: Cl.uint(1),
  "price-feeds": Cl.list([feedRecord(6, 100_000_000n, -8n, null, 1n, null, null)]),
});

// === PRODUCTION vector (live API capture) ==================================
// 3 feeds (BTC/ETH/SOL), each with price/exponent/confidence/best-bid/best-ask/
// publisher-count. Signed by Pyth's production signer.
const PROD_UPDATE = hexToBytes(
  "2a22999af2e2f11814d4a4a1c5ca99f68566d219cb1940a6197e9b93ed6b0a7d" +
    "06436f951d30d97e431783e5b91ce26b24b1f98084ef59748ac7816880606523" +
    "df2321ff00009b93c7d375000654503664b37001030000000106000000060f42" +
    "7d5d4104fff80500000000548ef2dc010000060f3a7d7d8d020000060f504bc4" +
    "a20300120000000206000000002a76c0d92a04fff8050000000002acd4240100" +
    "00002a76be3039020000002a76c1aabe03001300000006060000000001c03e9a" +
    "1c04fff80500000000001392e00100000001c0368bd60200000001c04118e403" +
    "0010",
);
const PROD_PAYLOAD = PROD_UPDATE.slice(71);
const PROD_SIGNER = "03a4380f01136eb2640f90c17e1e319e02bbafbeef2e6e67dc48af53f9827e155b";
const PROD_DECODE = Cl.tuple({
  timestamp: Cl.uint(1_781_553_346_950_000n),
  channel: Cl.uint(1),
  "price-feeds": Cl.list([
    feedRecord(1, 6_662_609_788_225n, -8n, 1_418_654_428n, 18n, 6_662_475_578_765n, 6_662_841_418_914n),
    feedRecord(2, 182_380_976_426n, -8n, 44_880_932n, 19n, 182_380_802_105n, 182_381_030_078n),
    feedRecord(6, 7_520_295_452n, -8n, 1_282_784n, 16n, 7_519_767_510n, 7_520_458_980n),
  ]),
});

describe("pyth-lazer-decoder-v1: REAL Lazer evm golden fixtures (byte-order anchor)", () => {
  it("STAGING: decode-payload matches Pyth's own decoded values (big-endian)", () => {
    const { result } = simnet.callReadOnlyFn(DECODER, "decode-payload", [Cl.buffer(STAGING_PAYLOAD)], deployer);
    expect(result).toBeOk(STAGING_DECODE);
  });

  it("STAGING: recover-signer recovers the staging signer's compressed pubkey", () => {
    const { result } = simnet.callReadOnlyFn(DECODER, "recover-signer", [Cl.buffer(STAGING_UPDATE)], deployer);
    expect(result).toBeOk(Cl.tuple({ signer: Cl.buffer(hexToBytes(STAGING_SIGNER)), payload: Cl.buffer(STAGING_PAYLOAD) }));
  });

  it("STAGING: decode-and-verify accepts the update end-to-end when its signer is trusted", () => {
    trust(STAGING_SIGNER);
    const { result } = simnet.callPublicFn(DECODER, "decode-and-verify-price-feeds", [Cl.buffer(STAGING_UPDATE)], deployer);
    expect(result).toBeOk(STAGING_DECODE);
  });

  it("PRODUCTION: decode-and-verify matches the SDK decode for a real multi-feed update", () => {
    trust(PROD_SIGNER);
    const { result } = simnet.callPublicFn(DECODER, "decode-and-verify-price-feeds", [Cl.buffer(PROD_UPDATE)], deployer);
    expect(result).toBeOk(PROD_DECODE);
  });

  it("PRODUCTION: recover-signer recovers the production signer's compressed pubkey", () => {
    const { result } = simnet.callReadOnlyFn(DECODER, "recover-signer", [Cl.buffer(PROD_UPDATE)], deployer);
    expect(result).toBeOk(Cl.tuple({ signer: Cl.buffer(hexToBytes(PROD_SIGNER)), payload: Cl.buffer(PROD_PAYLOAD) }));
  });

  it("rejects a real update when its signer is not trusted (the signer path is genuinely exercised)", () => {
    // No trust() seeding: an empty trusted-signer set must reject even valid bytes.
    const { result } = simnet.callPublicFn(DECODER, "decode-and-verify-price-feeds", [Cl.buffer(PROD_UPDATE)], deployer);
    expect(result).toBeErr(Cl.uint(ERR_UNTRUSTED_SIGNER));
  });
});
