import { describe, expect, it } from "vitest";
import { Cl } from "@stacks/transactions";
import { hexToBytes } from "@noble/hashes/utils";
import { readFileSync } from "node:fs";

// ---------------------------------------------------------------------------
// REAL Pyth Lazer `evm` golden fixtures -- the byte-order / endianness anchors.
//
// Two externally-produced vectors, neither generated by our own encoder:
//
//   STAGING -- pyth-network/pyth-crosschain lazer/contracts/evm/test/PythLazer.t.sol
//     (fn test_verify), commit fca047c66d4f38f9efd3601feeb93b733aad520d, v0.1.1.
//     Single feed, no confidence; staging signer.
//
//   PRODUCTION -- a real BTC/ETH/SOL update captured from the live Lazer API
//     (scripts/capture-base-properties.mjs -> tests/fixtures/captured/),
//     signed by Pyth's PRODUCTION signer. Multi-feed, with confidence + best-bid/ask
//     + publisher-count, so it confirms big-endian layout AND closes the multi-feed /
//     confidence(u64) coverage gaps on real production bytes.
//
// Matching Pyth's own decoded values confirms our parser against production data
// (PLAN Phase 5, sections 9-10).
// ---------------------------------------------------------------------------

const accounts = simnet.getAccounts();
const deployer = accounts.get("deployer")!;

const DECODER = "pyth-lazer-decoder-v1";
const ORACLE = "pyth-lazer-oracle";
const GOV = "pyth-lazer-oracle";
const decoderRef = Cl.contractPrincipal(deployer, DECODER);

const FAR_FUTURE = 100_000_000_000n; // unix seconds, ~year 5138 -- never expired
const ERR_UNTRUSTED_SIGNER = 2105;

const optInt = (v: bigint | null) => (v === null ? Cl.none() : Cl.some(Cl.int(v)));
const optUint = (v: bigint | null) => (v === null ? Cl.none() : Cl.some(Cl.uint(v)));

// Expected decoded per-feed tuple (full v1 shape). Every property is optional; a feed is never
// dropped for a missing one. These real updates carry only properties 0-5, so market-session /
// ema-* / funding-* / feed-update-timestamp are all `none`.
const feedRecord = (
  id: number,
  price: bigint | null,
  expo: bigint | null,
  conf: bigint | null,
  pub: bigint | null,
  bid: bigint | null,
  ask: bigint | null,
) =>
  Cl.tuple({
    "feed-id": Cl.uint(id),
    price: optInt(price),
    exponent: optInt(expo),
    confidence: optUint(conf),
    "publisher-count": optUint(pub),
    "best-bid": optInt(bid),
    "best-ask": optInt(ask),
    "funding-rate": Cl.none(),
    "funding-timestamp": Cl.none(),
    "funding-rate-interval": Cl.none(),
    "market-session": Cl.none(),
    "ema-price": Cl.none(),
    "ema-confidence": Cl.none(),
    "feed-update-timestamp": Cl.none(),
  });

function trust(signerHex: string) {
  simnet.callPublicFn(
    GOV,
    "set-trusted-signers",
    [Cl.list([Cl.tuple({ pubkey: Cl.buffer(hexToBytes(signerHex)), "expires-at": Cl.uint(FAR_FUTURE) })])],
    deployer,
  );
  // widen the staleness window so these real (past-dated) fixtures stay fresh through the oracle
  simnet.callPublicFn(ORACLE, "set-stale-price-threshold", [Cl.uint(100_000_000_000_000n)], deployer);
}

// === STAGING vector (PythLazer.t.sol v0.1.1) ===============================
// Properties (out of type order): Price, BestAsk(0), BestBid(0), PublisherCount(1),
// Exponent(-8); no confidence. BestBid/BestAsk are 0 -- Lazer's "missing" sentinel
// for optionals -- so they decode to `none` (decoder `some-if-nonzero-*`), matching
// the reference PythLazerLib (a 0 optional => ApplicableButMissing).
const STAGING_UPDATE = hexToBytes(
  "2a22999a9ee4e2a3df5affd0ad8c7c46c96d3b5ef197dd653bedd8f44a4b6b69" +
    "b767fbc66341e80b80acb09ead98c60d169b9a99657ebada101f447378f227bf" +
    "fbc69d3d01003493c7d37500062cf28659c1e801010000000605000000000005" +
    "f5e10002000000000000000001000000000000000003000104fff8",
);
const STAGING_PAYLOAD = STAGING_UPDATE.slice(71);
// Compressed pubkey recovered off-chain (eth 0xb8d50f0bAE75BF6E03c104903d7C3aFc4a6596Da).
const STAGING_SIGNER = "033fa670134f8f961047bf009e0e4907c79005fdf83eef5eef13d2f36bb5cd048b";
const STAGING_DECODE = Cl.tuple({
  timestamp: Cl.uint(1_738_270_008_001_000n),
  channel: Cl.uint(1),
  "price-feeds": Cl.list([feedRecord(6, 100_000_000n, -8n, null, 1n, null, null)]),
});

// === PRODUCTION vector (live API capture) ==================================
// 3 feeds (BTC/ETH/SOL), each with price/exponent/confidence/best-bid/best-ask/
// publisher-count. Signed by Pyth's production signer.
const PROD_UPDATE = hexToBytes(
  "2a22999af2e2f11814d4a4a1c5ca99f68566d219cb1940a6197e9b93ed6b0a7d" +
    "06436f951d30d97e431783e5b91ce26b24b1f98084ef59748ac7816880606523" +
    "df2321ff00009b93c7d375000654503664b37001030000000106000000060f42" +
    "7d5d4104fff80500000000548ef2dc010000060f3a7d7d8d020000060f504bc4" +
    "a20300120000000206000000002a76c0d92a04fff8050000000002acd4240100" +
    "00002a76be3039020000002a76c1aabe03001300000006060000000001c03e9a" +
    "1c04fff80500000000001392e00100000001c0368bd60200000001c04118e403" +
    "0010",
);
const PROD_PAYLOAD = PROD_UPDATE.slice(71);
const PROD_SIGNER = "03a4380f01136eb2640f90c17e1e319e02bbafbeef2e6e67dc48af53f9827e155b";
const PROD_DECODE = Cl.tuple({
  timestamp: Cl.uint(1_781_553_346_950_000n),
  channel: Cl.uint(1),
  "price-feeds": Cl.list([
    feedRecord(1, 6_662_609_788_225n, -8n, 1_418_654_428n, 18n, 6_662_475_578_765n, 6_662_841_418_914n),
    feedRecord(2, 182_380_976_426n, -8n, 44_880_932n, 19n, 182_380_802_105n, 182_381_030_078n),
    feedRecord(6, 7_520_295_452n, -8n, 1_282_784n, 16n, 7_519_767_510n, 7_520_458_980n),
  ]),
});

// === PRODUCTION 75-feed vector (live API capture at MAX_FEEDS) ==============
// A real fixed_rate@1000ms update carrying 75 crypto feeds -- the raised MAX_FEEDS, on
// production bytes. Expected values are derived from Pyth's own parsed output, mirroring the
// decoder (required price/exponent/publisher-count; 0 -> none for price/bid/ask/conf/pub),
// so the assertion stays correct if the fixture is re-captured. Captured via
// scripts/capture-max-feeds.mjs.
const MAXFEEDS = JSON.parse(readFileSync("tests/fixtures/captured/1784755513000000.json", "utf8"));
const MAXFEEDS_UPDATE = hexToBytes(MAXFEEDS.evmHex.replace(/^0x/, ""));

const bi = (v: string | number | null | undefined) => (v == null ? null : BigInt(v));
const nz = (v: bigint | null) => (v === null || v === 0n ? null : v); // decoder's some-if-nonzero

type ParsedFeed = {
  priceFeedId: number;
  price?: string | null;
  bestBidPrice?: string | null;
  bestAskPrice?: string | null;
  publisherCount?: number | null;
  exponent?: number | null;
  confidence?: number | null;
};

const expectedFeeds = (feeds: ParsedFeed[]) =>
  feeds.map((f) =>
    feedRecord(
      f.priceFeedId,
      nz(bi(f.price)), // price: Option<Price>, 0/absent -> none
      bi(f.exponent), // exponent: i16, 0 kept; absent -> none
      nz(bi(f.confidence)),
      bi(f.publisherCount), // publisher-count: u16, 0 kept; absent -> none
      nz(bi(f.bestBidPrice)),
      nz(bi(f.bestAskPrice)),
    ),
  );

const MAXFEEDS_DECODE = Cl.tuple({
  timestamp: Cl.uint(BigInt(MAXFEEDS.timestampUs)),
  channel: Cl.uint(MAXFEEDS.channel),
  "price-feeds": Cl.list(expectedFeeds(MAXFEEDS.parsed.priceFeeds)),
});

describe("pyth-lazer-decoder-v1: REAL Lazer evm golden fixtures (byte-order anchor)", () => {
  it("STAGING: decode-lazer-payload matches Pyth's own decoded values (big-endian)", () => {
    const { result } = simnet.callReadOnlyFn(DECODER, "decode-lazer-payload", [Cl.buffer(STAGING_PAYLOAD)], deployer);
    expect(result).toBeOk(STAGING_DECODE);
  });

  it("STAGING: recover-signer recovers the staging signer's compressed pubkey", () => {
    const { result } = simnet.callReadOnlyFn(DECODER, "recover-signer", [Cl.buffer(STAGING_UPDATE)], deployer);
    expect(result).toBeOk(Cl.tuple({ signer: Cl.buffer(hexToBytes(STAGING_SIGNER)), payload: Cl.buffer(STAGING_PAYLOAD) }));
  });

  it("STAGING: decode-and-verify accepts the update end-to-end when its signer is trusted", () => {
    trust(STAGING_SIGNER);
    const { result } = simnet.callPublicFn(ORACLE, "verify-price-feeds", [Cl.buffer(STAGING_UPDATE), decoderRef, Cl.none()], deployer);
    expect(result).toBeOk(STAGING_DECODE);
  });

  it("PRODUCTION: decode-and-verify matches the SDK decode for a real multi-feed update", () => {
    trust(PROD_SIGNER);
    const { result } = simnet.callPublicFn(ORACLE, "verify-price-feeds", [Cl.buffer(PROD_UPDATE), decoderRef, Cl.none()], deployer);
    expect(result).toBeOk(PROD_DECODE);
  });

  it("PRODUCTION: recover-signer recovers the production signer's compressed pubkey", () => {
    const { result } = simnet.callReadOnlyFn(DECODER, "recover-signer", [Cl.buffer(PROD_UPDATE)], deployer);
    expect(result).toBeOk(Cl.tuple({ signer: Cl.buffer(hexToBytes(PROD_SIGNER)), payload: Cl.buffer(PROD_PAYLOAD) }));
  });

  it("PRODUCTION 75-feed: decode-and-verify matches the SDK decode at MAX_FEEDS (real bytes)", () => {
    expect(MAXFEEDS.parsed.priceFeeds.length).toBe(75); // capture sits exactly at the cap
    trust(PROD_SIGNER);
    const { result } = simnet.callPublicFn(ORACLE, "verify-price-feeds", [Cl.buffer(MAXFEEDS_UPDATE), decoderRef, Cl.none()], deployer);
    expect(result).toBeOk(MAXFEEDS_DECODE);
  });

  it("rejects a real update when its signer is not trusted (the signer path is genuinely exercised)", () => {
    // No trust() seeding: an empty trusted-signer set must reject even valid bytes.
    const { result } = simnet.callPublicFn(ORACLE, "verify-price-feeds", [Cl.buffer(PROD_UPDATE), decoderRef, Cl.none()], deployer);
    expect(result).toBeErr(Cl.uint(ERR_UNTRUSTED_SIGNER));
  });
});
